# Generated by Django 3.2.6 on 2021-08-05 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidades_disponibles', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('fecha_introduccion', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(default=None)),
            ],
        ),
    ]
