# Generated by Django 3.2.6 on 2021-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_modificacion',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
