# Generated by Django 3.2.6 on 2021-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_producto_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_introduccion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
