# Generated by Django 3.2.6 on 2021-08-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210807_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=30, null=True)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='tiendas/')),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.direccion')),
            ],
        ),
    ]
