# Generated by Django 3.2.6 on 2021-08-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pedido_pedidoentregapostal_pedidoentregatienda_productopedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nota',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoentregatienda',
            name='codigo_recogida',
            field=models.CharField(max_length=6),
        ),
    ]
